fixed scripts

diff --git a/runner/run b/runner/run
--- a/runner/run
+++ b/runner/run
@@ -75,10 +75,20 @@ extract_params() {
 
 # Function to initialize directories and paths
 initialize_paths() {
-    CWD=$(pwd)
     SHARE=$(echo "$SHARE_VALUE" | awk -F'/' '{print $1}')
 
-    DATA_DIR="${CWD}/data"
+    if [[ -z "${DATA_DIR}" ]]; then
+      echo "ERROR: DATA_DIR environment variable is not set."
+      exit 1
+    fi
+
+    if [[ -z "${BIN_PATH}" ]]; then
+      echo "ERROR: BIN_PATH environment variable is not set."
+      exit 1
+    fi
+
+    echo "Using data directory: ${DATA_DIR}"
+
     OUT_FILE="${DATA_DIR}/out${BITS}.txt"
     CP_FILE="${DATA_DIR}/cp-${BITS}-${SHARE}.txt"
     PARAMS_FILE="${DATA_DIR}/params.txt"
@@ -105,7 +115,9 @@ execute_command() {
 
 # Main script execution
 main() {
-    BIN_PATH="../bin/cuBitCrack"
+    # Initialized in Dockerfile
+    # DATA_DIR=$DATA_DIR
+    # BIN_PATH=$BIN_PATH
     
     # Initialize constants
     D_BLOCKS=512
diff --git a/scripts/init_data_bucket b/scripts/init_data_bucket
--- a/scripts/init_data_bucket
+++ b/scripts/init_data_bucket
@@ -1,7 +1,12 @@
 #!/bin/bash
 
-if [[-z "${GOOGLE_BUCKET_NAME}" ]]; then
+if [[ -z "${GOOGLE_BUCKET_NAME}" ]]; then
   echo "ERROR: GOOGLE_BUCKET_NAME environment variable is not set."
+  exit 1
+fi
+
+if [[ -z "${DATA_DIR}" ]]; then
+  echo "ERROR: DATA_DIR environment variable is not set."
   exit 1
 fi
 
@@ -9,7 +14,8 @@ fi
 # Vast.ai only allows 256 characters in an environment variable
 # Service account credentials are split into 12 environment variables as base64 encoded strings
 for i in $(seq 1 12); do
-  if [[ -z "${GOOGLE_SERVICE_ACCT_CREDENTIALS_$i}" ]]; then
+  eval varr=\$GOOGLE_SERVICE_ACCT_CREDENTIALS_$i
+  if [[ -z "$varr" ]]; then
     echo "ERROR: GOOGLE_SERVICE_ACCT_CREDENTIALS_$i environment variable is not set."
     exit 1
   fi
@@ -18,7 +24,8 @@ done
 # Assemble the base64 string of service account credentials
 GOOGLE_SERVICE_ACCT_CONTENTS=""
 for i in $(seq 1 12); do
-    GOOGLE_SERVICE_ACCT_CONTENTS+="${!GOOGLE_SERVICE_ACCT_CREDENTIALS_$i}"
+  eval varr=\$GOOGLE_SERVICE_ACCT_CREDENTIALS_$i
+  GOOGLE_SERVICE_ACCT_CONTENTS+="$varr"
 done
 
 # Servie account credentials path
@@ -28,7 +35,14 @@ CREDENTIALS_PATH="/tmp/service_account.json"
 echo "$GOOGLE_SERVICE_ACCT_CONTENTS" | base64 -d > $CREDENTIALS_PATH
 
 # Mount path
-MOUNT_PATH="./data"
+MOUNT_PATH=$DATA_DIR
+
+# Create Dir
+mkdir -p $MOUNT_PATH
+
+# Give permission to group
+chmod g+w $MOUNT_PATH
+
 
 
 # Initialize gcloud with service account
